#!/usr/bin/env bash
#
# Functions for the Host Virtual Machine Console CLI
#
# Cy Rossignol <cy@rossignols.me>
#

# if not running under Cygwin
if [[ -z ${CYGDIR+x} ]]; then
    source "$KICKBOXER/shared/scripts/functions"
else
    source "$(cygpath $KICKBOXER)/shared/scripts/functions"
fi

vm_load_adapter_for_vm() {
    # Choose the virtualization platform (only VirtualBox supported at this time)
    source "$(vm_path)/host/scripts/vbox_adapter"

    if ! vm_host_exists; then
        echo "Could not find Virtual Machine Host Application ${VM_HOST_APP}."
        echo "Please install ${VM_HOST_APP} or add the location of the"
        echo "application to your environment's PATH."

        return 1
    fi

    if ! vm_manager_exists; then
        echo "Could not find Virtual Machine Manager Application ${VM_MANAGER}."
        echo "Please install ${VM_HOST_APP} or add the location of the"
        echo "application to your environment's PATH."

        return 1
    fi
}
